payload:
  # GeoSites
  - GEOSITE,apple
  - GEOSITE,amazon
  - GEOSITE,atlassian
  - GEOSITE,bing
  - GEOSITE,bing@cn
  - GEOSITE,discord
  - GEOSITE,godaddy
  - GEOSITE,google
  - GEOSITE,facebook
  - GEOSITE,github
  - GEOSITE,gitlab
  - GEOSITE,gravatar
  - GEOSITE,microsoft
  - GEOSITE,microsoft@cn
  - GEOSITE,linkedin
  - GEOSITE,slack
  - GEOSITE,tiktok
  - GEOSITE,twitter
  - GEOSITE,youtube

  # General sites
  - DOMAIN-SUFFIX,1password.com # 1Password
  - DOMAIN-SUFFIX,monica.im # Monica
  - DOMAIN-SUFFIX,monica-cdn.im # Monica
  - DOMAIN-SUFFIX,ansible.com # Ansible
  - DOMAIN-SUFFIX,discourse-cdn.com # Discourse
  - DOMAIN-SUFFIX,hypothes.is # Hypothesis
  - DOMAIN-SUFFIX,inoreader.com # Inoreader
  - DOMAIN-SUFFIX,jsfiddle.net # JSFiddle
  - DOMAIN-SUFFIX,jwt.io # JWT
  - DOMAIN-SUFFIX,linuxfoundation.org # Linux Foundation
  - DOMAIN-SUFFIX,medium.com # Medium
  - DOMAIN-SUFFIX,objectpath.org # ObjectPath
  - DOMAIN-SUFFIX,obsidian.md # Obsidian
  - DOMAIN-SUFFIX,pagerduty.com # PagerDuty
  - DOMAIN-SUFFIX,stackexchange.com # StackExchange
  - DOMAIN-SUFFIX,zerotier.com # Zerotier
  - DOMAIN-SUFFIX,dynatrace.com # Dynatrace
  - DOMAIN-SUFFIX,ultramobile.com # Ultra Mobile
  - DOMAIN-SUFFIX,open.xiaojingai.com # 小鲸AI
