[General]
loglevel = notify
hijack-dns = *:53
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
skip-proxy = localhost, *.local, *.kang.zone, *.paymaya.com, *.ap-southeast-1.eks.amazonaws.com, *.voyagerapis.com, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
dns-server = 119.29.29.29, 223.5.5.5, 1.1.1.1, 8.8.8.8
encrypted-dns-server = https://durable0762.com:44443/dns-query, https://delirium9599.com:44443/dns-query, https://cf-cdn.delirium9599.com:443/dns-query, https://doh.pub/dns-query
proxy-test-url = http://1.1.1.1/generate_204
test-timeout = 5

[Proxy Group]
DEFAULT = url-test, policy-path=mitce.conf, policy-regex-filter=(台湾|新加坡|TW|KR|SG|JP), update-interval=86400, interval=600, tolerance=100
TRAFFIC = url-test, policy-path=sntp.conf, policy-regex-filter=TW|HK, update-interval=86400, interval=600, tolerance=100
NETSKOPE = url-test, policy-path=tag.conf, policy-regex-filter=1x, update-interval=86400, interval=600, tolerance=100
CLEANIP = select, policy-path=tag.conf, policy-regex-filter=(阿什本|夏洛特|斯波坎|家宽), update-interval=86400, interval=600, tolerance=100
GAMING = select, policy-path=tag.conf, policy-regex-filter=游戏, update-interval=86400, interval=600, tolerance=100
USA = select, policy-path=tag.conf, policy-regex-filter=(阿什本|夏洛特|斯波坎), update-interval=86400, interval=600, tolerance=100

[Rule]
# RULE-SET,https://surge.bojin.co/geosite/category-ads-all,REJECT
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/traffic.list,TRAFFIC
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/cleanip.list,CLEANIP
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/gaming.list,GAMING
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/netskope.list,NETSKOPE
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/usa.list,USA
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/default.list,DEFAULT
RULE-SET,https://raw.githubusercontent.com/kangeek/proxy-config/refs/heads/main/surge/rule_set/direct.list,DIRECT
FINAL,DEFAULT

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^http://(www.)?g.cn https://www.google.com 302
^http://(www.)?google.cn https://www.google.com 302

[SSID Setting]
PANDORA suspend=true
